<a href="https://colab.research.google.com/github/sunilahire55/IITP-Coding/blob/main/The_key_concepts_for_evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print()

In [ ]:
print("Hello Friends")

Hello Friends

In [ ]:
print(2+3)

5

In [ ]:
print("Hi","Bye")

Hi Bye

In [ ]:
A = int(input())
B = int(input())
print(A + B)

3
5
8

In [ ]:
A = str(input())
B = str(input())
print(A + B)

5
3
53

In [ ]:

# This is the single-line comment

x = 10 #inline comment

In [ ]:
if 2 > 1:
print("True Block")
print("Always runs")

IndentationError: expected an indented block after 'if' statement on line 1 (2672083047.py, line 2)

In [ ]:
marks = 91
if marks >= 90:
  print("A")
elif marks >= 75:
  print("B")
else:
  print("C")

A

In [28]:
marks = 90
if marks >= 90:
  print("A")
elif marks >= 75:
  print("B")
elif marks >= 60:
  print("C")
else:
  print("D")

A

In [30]:
i = 5
while i >= 1:
  print(i)
  i -=  1

5
4
3
2
1

In [38]:
for i in range(0,10,2):
  print(i)

0
2
4
6
8

In [45]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9

In [46]:
10%3

1

In [53]:
7%2

1

In [54]:
8%2

0

In [67]:
num = 10%3
if num % 2 == 1:
 print("ODD")

ODD

In [74]:
for i in range(0,7):
  if i == 3:
    continue
  print(i)

0
1
2
4
5
6

In [80]:
for i in range(1,7):
  if i ==9:
    break
  print(i)

1
2
3
4
5
6

In [85]:
marks = [55,60,32,90,100]
print(marks[0]) #55 (first element)
print(marks[-1]) #100 (last element)
print(marks[-3]) #32 (third element)

55
100
32

In [86]:
print(marks[0:3])

[55, 60, 32]

In [87]:
print(marks[::2])

[55, 32, 100]

In [95]:
print(marks[::])

[55, 60, 32, 90, 100]

In [96]:
marks[2] = 75

In [97]:
print(marks)

[55, 60, 75, 90, 100]

In [98]:
marks.append(70)

In [99]:
print(marks)

[55, 60, 75, 90, 100, 70]

In [103]:
marks.pop(2)

90

In [104]:
t = (5,8,2)

In [106]:
print(t[2])

2

In [107]:
student = {"name": "Ravi", "age":20, "city":"mumbai"}

In [108]:
print(student)

{'name': 'Ravi', 'age': 20, 'city': 'mumbai'}

In [109]:
print(student["name"])

Ravi

In [111]:
print(student["age"])

20

In [112]:
print(student.get("CGPA"))

None

In [113]:
print(student.get("CGPA", "not found"))

not found

In [114]:
student["CGPA"] = 9.8

In [115]:
print(student)

{'name': 'Ravi', 'age': 20, 'city': 'mumbai', 'CGPA': 9.8}

In [116]:
student["name"] = "sunil"

In [117]:
print(student)

{'name': 'sunil', 'age': 20, 'city': 'mumbai', 'CGPA': 9.8}

In [118]:
student.update({"age": 35, "city":"Delhi"})

In [119]:
print(student)

{'name': 'sunil', 'age': 35, 'city': 'Delhi', 'CGPA': 9.8}

In [120]:
print(len(student))

4

In [121]:
fruits = {'apple', 'banana', 'strawberry', 'apple'}

In [122]:
print(fruits)

{'strawberry', 'banana', 'apple'}

In [123]:
fruits.add('orange')

In [124]:
print(fruits)

{'orange', 'strawberry', 'banana', 'apple'}

In [125]:
fruits.remove('banana')

In [126]:
print(fruits)

{'orange', 'strawberry', 'apple'}

In [127]:
fruits.discard('banana')

In [128]:
print(fruits)

{'orange', 'strawberry', 'apple'}

In [130]:
fruits.add('banana')

In [131]:
print(fruits)

{'orange', 'strawberry', 'banana', 'apple'}

In [132]:
fruits.discard('banana')

In [133]:
print(fruits)

{'orange', 'strawberry', 'apple'}

In [134]:
fruits.pop()

'orange'

In [135]:
print(fruits)

{'strawberry', 'apple'}

In [136]:
fruits.pop()

'strawberry'

In [137]:
print(fruits)

{'apple'}

In [139]:
fruits.add('banana')

In [140]:
fruits.add('strawberry')

In [141]:
print(student)

{'name': 'sunil', 'age': 35, 'city': 'Delhi', 'CGPA': 9.8}

In [142]:
print(fruits)

{'strawberry', 'banana', 'apple'}

In [144]:
s1.update(s2)
print(student)

NameError: name 's1' is not defined

In [145]:
s1 = {1,2,3,4}
s2 = {3,4,5,6}

In [148]:
s1.update(s2)

In [149]:
print(s1)

{1, 2, 3, 4, 5, 6}

In [155]:
print(s2)

{3, 4, 5, 6}

In [151]:
s3 = s1.union(s2)

In [152]:
print(s3)

{1, 2, 3, 4, 5, 6}

In [156]:
s4 = s1.intersection(s2)

In [157]:
print(s4)

{3, 4, 5, 6}

In [158]:
'apple' in fruits

True

In [161]:
'lemon' in  fruits

False

In [163]:
for fruit in fruits:
  print(fruit)

strawberry
banana
apple

In [164]:
# Defining and Calling Functions

In [165]:
def greet():
  print("Hello")

In [166]:
greet()

Hello

In [167]:
def greet():
  print("SUnil")

In [168]:
greet()

SUnil

In [173]:
def add(a,b):
  return a+b

add(4,5)

9

In [180]:
def profile(name, age):
  print(f"Name: {name}, Age: {age}")
profile(name='raj',age=35 )

Name: raj, Age: 35

In [181]:
def interest_rate(rate=10):
  print(f"Rate: {rate}")

In [182]:
interest_rate()

Rate: 10

In [183]:
interest_rate(15)

Rate: 15

In [203]:
class Student:
  def __init__(self, name, age):
    self.name = name
    self.age = age

s5 = Student("Sairaj", 20)
s6 = Student("Sunil", 22)

print(s5.name)
print(s6.name)

Sairaj
Sunil

In [204]:
import math

In [205]:
import math as m

In [206]:
from math import sqrt

In [207]:
python -m venv myenv

SyntaxError: invalid syntax (2600529532.py, line 1)

In [208]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([[1,2,3], [4,5,6]])

print(type(b))

<class 'numpy.ndarray'>

In [209]:
print(b.shape)

(2, 3)

In [210]:
print(a.shape)

(5,)

In [211]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [212]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [213]:
a = np.array([10,20,30,40,50])

In [214]:
a[0]

np.int64(10)

In [215]:
a[3]

np.int64(40)

In [216]:
a[-1]

np.int64(50)

In [217]:
a[1:4]

array([20, 30, 40])

In [218]:
b = np.array([[1,2,3,],[4,5,6],[7,8,9]])

In [219]:
b[0,2]

np.int64(3)

In [221]:
b[:,1]

array([2, 5, 8])

In [222]:
b[0:2,1:]

array([[2, 3],
       [5, 6]])

In [226]:
a = np.array([3,8,1,6,4])

In [227]:
mask = a > 4

In [228]:
a[mask]

array([8, 6])

In [229]:
a[a>4]

array([8, 6])

In [231]:
a[a>5] = -1

In [232]:
a

array([3, 1, 1, 1, 4])

In [233]:
a = np.array([3,8,1,6,4])

In [234]:
np.mean(a)

np.float64(4.4)

In [235]:
np.std(a)

np.float64(2.4166091947189146)

In [236]:
np.max(a)

np.int64(8)

In [237]:
np.min(a)

np.int64(1)

In [238]:
np.argmax(a)

np.int64(1)

In [239]:
b = np.array([[1,2],[3,4]])

In [240]:
np.mean(b)

np.float64(2.5)

In [241]:
np.mean(b, axis=0)

array([2., 3.])

In [243]:
np.mean(b, axis=1)

array([1.5, 3.5])

In [244]:
import pandas as pd

s = pd.Series([10,45,21])
print(s)

0    10
1    45
2    21
dtype: int64

In [246]:
data = {'Name':['Sunil', 'Sairaj'], 'Age':[18,20]}

In [247]:
df = pd.DataFrame(data)

In [263]:
data['Age']

[18, 20]

In [270]:
data[['Name', 'Age']]

TypeError: unhashable type: 'list'

In [271]:
df.isnull()

          A      B
row1  False  False
row2  False  False
row3  False  False

In [272]:
df.dropna()

      A  B
row1  2  3
row2  4  5
row3  6  7

In [273]:
print(df)

      A  B
row1  2  3
row2  4  5
row3  6  7

In [275]:
df.fillna(0)

      A  B
row1  2  3
row2  4  5
row3  6  7